<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $country = [

            ['shortname'=>'AF', 'name'=>'Afghanistan', 'phone_code'=>'+93', 'status' =>'1'],
            ['shortname'=>'AL', 'name'=>'Albania', 'phone_code'=>'+355', 'status' =>'1'],
            ['shortname'=>'DJ', 'name'=>'Algeria', 'phone_code'=>'+213', 'status' =>'1'],
            ['shortname'=>'AS', 'name'=>'American Samoa', 'phone_code'=>'+1684', 'status' =>'1'],
            ['shortname'=>'AD', 'name'=>'Andorra', 'phone_code'=>'+376', 'status' =>'1'],
            ['shortname'=>'AO', 'name'=>'Angola', 'phone_code'=>'+244', 'status' =>'1'],
            ['shortname'=>'AI', 'name'=>'Anguilla', 'phone_code'=>'+1264', 'status' =>'1'],
            ['shortname'=>'AQ', 'name'=>'Antarctica', 'phone_code'=>'+0', 'status' =>'1'],
            ['shortname'=>'AG', 'name'=>'Antigua And Barbuda', 'phone_code'=>'+1268', 'status' =>'1'],
            ['shortname'=>'AR', 'name'=>'Argentina', 'phone_code'=>'+54', 'status' =>'1'],
            ['shortname'=>'AM', 'name'=>'Armenia', 'phone_code'=>'+374', 'status' =>'1'],
            ['shortname'=>'AW', 'name'=>'Aruba', 'phone_code'=>'+297', 'status' =>'1'],
            ['shortname'=>'AU', 'name'=>'Australia', 'phone_code'=>'+61', 'status' =>'1'],
            ['shortname'=>'AT', 'name'=>'Austria', 'phone_code'=>'+43', 'status' =>'1'],
            ['shortname'=>'AZ', 'name'=>'Azerbaijan', 'phone_code'=>'+994', 'status' =>'1'],
            ['shortname'=>'BS', 'name'=>'Bahamas The', 'phone_code'=>'+1242', 'status' =>'1'],
            ['shortname'=>'BH', 'name'=>'Bahrain', 'phone_code'=>'+973', 'status' =>'1'],
            ['shortname'=>'BD', 'name'=>'Bangladesh', 'phone_code'=>'+880', 'status' =>'1'],
            ['shortname'=>'BB', 'name'=>'Barbados', 'phone_code'=>'+1246', 'status' =>'1'],
            ['shortname'=>'BY', 'name'=>'Belarus', 'phone_code'=>'+375', 'status' =>'1'],
            ['shortname'=>'BE', 'name'=>'Belgium', 'phone_code'=>'+32', 'status' =>'1'],
            ['shortname'=>'BZ', 'name'=>'Belize', 'phone_code'=>'+501', 'status' =>'1'],
            ['shortname'=>'BJ', 'name'=>'Benin', 'phone_code'=>'+299', 'status' =>'1'],
            ['shortname'=>'BM', 'name'=>'Bermuda', 'phone_code'=>'+1441', 'status' =>'1'],
            ['shortname'=>'BT', 'name'=>'Bhutan', 'phone_code'=>'+975', 'status' =>'1'],
            ['shortname'=>'BO', 'name'=>'Bolivia', 'phone_code'=>'+591', 'status' =>'1'],
            ['shortname'=>'BA', 'name'=>'Bosnia and Herzegovina', 'phone_code'=>'+387', 'status' =>'1'],
            ['shortname'=>'Bw', 'name'=>'Botswana', 'phone_code'=>'+267', 'status' =>'1'],
            ['shortname'=>'BV', 'name'=>'Bouvet Island', 'phone_code'=>'+0', 'status' =>'1'],
            ['shortname'=>'BR', 'name'=>'Brazil', 'phone_code'=>'+55', 'status' =>'1'],
            ['shortname'=>'IO', 'name'=>'British Indian Ocean Territory', 'phone_code'=>'+246', 'status' =>'1'],
            ['shortname'=>'BN', 'name'=>'Brunei', 'phone_code'=>'+673', 'status' =>'1'],
            ['shortname'=>'BG', 'name'=>'Bulgaria', 'phone_code'=>'+359', 'status' =>'1'],
            ['shortname'=>'BF', 'name'=>'Burkina Faso', 'phone_code'=>'+226', 'status' =>'1'],
            ['shortname'=>'BI', 'name'=>'Burundi', 'phone_code'=>'+257', 'status' =>'1'],
            ['shortname'=>'KH', 'name'=>'Cambodia', 'phone_code'=>'+855', 'status' =>'1'],
            ['shortname'=>'CM', 'name'=>'Cameroon', 'phone_code'=>'+237', 'status'=>'1'],
            ['shortname'=>'CA', 'name'=>'Canada', 'phone_code'=>'+1', 'status'=>'1'],
            ['shortname'=>'CV', 'name'=>'Cape Verde', 'phone_code'=>'+238', 'status'=>'1'],
            ['shortname'=>'KY', 'name'=>'Cayman Islands', 'phone_code'=>'+1345', 'status'=>'1'],
            ['shortname'=>'CF', 'name'=>'Central African Republic', 'phone_code'=>'+236', 'status'=>'1'],
            ['shortname'=>'TD', 'name'=>'Chad', 'phone_code'=>'+235', 'status'=>'1'],
            ['shortname'=>'CL', 'name'=>'Chile', 'phone_code'=>'+56', 'status'=>'1'],
            ['shortname'=>'CN', 'name'=>'China', 'phone_code'=>'+86', 'status'=>'1'],
            ['shortname'=>'CX', 'name'=>'Christmas Island', 'phone_code'=>'+61 ', 'status'=>'1'],
            ['shortname'=>'CC', 'name'=>'Cocos', 'phone_code'=>'+672', 'status'=>'1'],
            ['shortname'=>'CO', 'name'=>'Colombia', 'phone_code'=>'+57', 'status'=>'1'],
            ['shortname'=>'KM', 'name'=>'Comoros', 'phone_code'=>'+269', 'status'=>'1'],
            ['shortname'=>'CG', 'name'=>'Republic Of The Congo', 'phone_code'=>'+242', 'status'=>'1'],
            ['shortname'=>'CD', 'name'=>'Democratic Republic Of The Congo', 'phone_code'=>'+242', 'status'=>'1'],
            ['shortname'=>'CK', 'name'=>'Cook Islands', 'phone_code'=>'+682 ', 'status'=>'1'],
            ['shortname'=>'CR', 'name'=>'Costa Rica', 'phone_code'=>'+506 ', 'status'=>'1'],
            ['shortname'=>'CI', 'name'=>'Cote D\'Ivoire (Ivory Coast)', 'phone_code'=>'+225', 'status'=>'1'],
            ['shortname'=>'HR', 'name'=>'Croatia', 'phone_code'=>'+385 ', 'status'=>'1'],
            ['shortname'=>'CU', 'name'=>'Cuba', 'phone_code'=>'+53 ', 'status'=>'1'],
            ['shortname'=>'CY', 'name'=>'Cyprus', 'phone_code'=>'+357 ', 'status'=>'1'],
            ['shortname'=>'CZ', 'name'=>'Czech Republic', 'phone_code'=>'+420', 'status'=>'1'],
            ['shortname'=>'DK', 'name'=>'Denmark', 'phone_code'=>'+45', 'status'=>'1'],
            ['shortname'=>'DJ', 'name'=>'Djibouti', 'phone_code'=>'+253', 'status'=>'1'],
            ['shortname'=>'DM', 'name'=>'Dominica', 'phone_code'=>'+1767', 'status'=>'1'],
            ['shortname'=>'DO', 'name'=>'Dominican Republic', 'phone_code'=>'+1809', 'status'=>'1'],
            ['shortname'=>'TP', 'name'=>'East Timor', 'phone_code'=>'+670', 'status'=>'1'],
            ['shortname'=>'EC', 'name'=>'Ecuador', 'phone_code'=>'+593', 'status'=>'1'],
            ['shortname'=>'EG', 'name'=>'Egypt', 'phone_code'=>'+20', 'status'=>'1'],
            ['shortname'=>'SV', 'name'=>'El Salvador', 'phone_code'=>'+503', 'status'=>'1'],
            ['shortname'=>'GQ', 'name'=>'Equatorial Guinea', 'phone_code'=>'+240', 'status'=>'1'],
            ['shortname'=>'ER', 'name'=>'Eritrea', 'phone_code'=>'+291', 'status'=>'1'],
            ['shortname'=>'EE', 'name'=>'Estonia', 'phone_code'=>'+372', 'status'=>'1'],
            ['shortname'=>'ET', 'name'=>'Ethiopia', 'phone_code'=>'+251', 'status'=>'1'],
            ['shortname'=>'XA', 'name'=>'External Territories of Australia', 'phone_code'=>'+61', 'status'=>'1'],
            ['shortname'=>'FK', 'name'=>'Falkland Islands', 'phone_code'=>'+500', 'status'=>'1'],
            ['shortname'=>'FO', 'name'=>'Faroe Islands', 'phone_code'=>'+298', 'status'=>'1'],
            ['shortname'=>'FJ', 'name'=>'Fiji Islands', 'phone_code'=>'+679', 'status'=>'1'],
            ['shortname'=>'FI', 'name'=>'Finland', 'phone_code'=>'+358', 'status'=>'1'],
            ['shortname'=>'FR', 'name'=>'France', 'phone_code'=>'+33', 'status'=>'1'],
            ['shortname'=>'GF', 'name'=>'French Guiana', 'phone_code'=>'+594', 'status'=>'1'],
            ['shortname'=>'PF', 'name'=>'French Polynesia', 'phone_code'=>'+689', 'status'=>'1'],
            ['shortname'=>'TF', 'name'=>'French Southern Territories', 'phone_code'=>'+0', 'status'=>'1'],
            ['shortname'=>'GA', 'name'=>'Gabon', 'phone_code'=>'+241', 'status'=>'1'],
            ['shortname'=>'GM', 'name'=>'Gambia The', 'phone_code'=>'+220', 'status'=>'1'],
            ['shortname'=>'GE', 'name'=>'Georgia', 'phone_code'=>'+995', 'status'=>'1'],
            ['shortname'=>'DE', 'name'=>'Germany', 'phone_code'=>'+49', 'status'=>'1'],
            ['shortname'=>'GH', 'name'=>'Ghana', 'phone_code'=>'+233', 'status'=>'1'],
            ['shortname'=>'GI', 'name'=>'Gibraltar', 'phone_code'=>'+350', 'status'=>'1'],
            ['shortname'=>'GR', 'name'=>'Greece', 'phone_code'=>'+30', 'status'=>'1'],
            ['shortname'=>'GL', 'name'=>'Greenland', 'phone_code'=>'+299', 'status'=>'1'],
            ['shortname'=>'GD', 'name'=>'Grenada', 'phone_code'=>'+1473', 'status'=>'1'],
            ['shortname'=>'GP', 'name'=>'Guadeloupe', 'phone_code'=>'+590', 'status'=>'1'],
            ['shortname'=>'GU', 'name'=>'Guam', 'phone_code'=>'+1671', 'status'=>'1'],
            ['shortname'=>'GT', 'name'=>'Guatemala', 'phone_code'=>'+502', 'status'=>'1'],
            ['shortname'=>'XU', 'name'=>'Guernsey and Alderney', 'phone_code'=>'+44', 'status'=>'1'],
            ['shortname'=>'GN', 'name'=>'Guinea', 'phone_code'=>'+224', 'status'=>'1'],
            ['shortname'=>'GW', 'name'=>'Guinea-Bissau', 'phone_code'=>'+245', 'status'=>'1'],
            ['shortname'=>'GY', 'name'=>'Guyana', 'phone_code'=>'+592', 'status'=>'1'],
            ['shortname'=>'HT', 'name'=>'Haiti', 'phone_code'=>'+509', 'status'=>'1'],
            ['shortname'=>'HM', 'name'=>'Heard and McDonald Islands', 'phone_code'=>'+0', 'status'=>'1'],
            ['shortname'=>'HN', 'name'=>'Honduras', 'phone_code'=>'+504', 'status'=>'1'],
            ['shortname'=>'HK', 'name'=>'Hong Kong S.A.R.', 'phone_code'=>'+852', 'status'=>'1'],
            ['shortname'=>'HU', 'name'=>'Hungary', 'phone_code'=>'+36', 'status'=>'1'],
            ['shortname'=>'IS', 'name'=>'Iceland', 'phone_code'=>'+354', 'status'=>'1'],
            ['shortname'=>'IN', 'name'=>'India', 'phone_code'=>'+91', 'status'=>'1'],
            ['shortname'=>'ID', 'name'=>'Indonesia', 'phone_code'=>'+62', 'status'=>'1'],
            ['shortname'=>'IR', 'name'=>'Iran', 'phone_code'=>'+98', 'status'=>'1'],
            ['shortname'=>'IQ', 'name'=>'Iraq', 'phone_code'=>'+964', 'status'=>'1'],
            ['shortname'=>'IE', 'name'=>'Ireland', 'phone_code'=>'+353', 'status'=>'1'],
            ['shortname'=>'IL', 'name'=>'Israel', 'phone_code'=>'+972', 'status'=>'1'],
            ['shortname'=>'IT', 'name'=>'Italy', 'phone_code'=>'+39', 'status'=>'1'],
            ['shortname'=>'JM', 'name'=>'Jamaica', 'phone_code'=>'+1876', 'status'=>'1'],
            ['shortname'=>'JP', 'name'=>'Japan', 'phone_code'=>'+81', 'status'=>'1'],
            ['shortname'=>'XJ', 'name'=>'Jersey', 'phone_code'=>'+44', 'status'=>'1'],
            ['shortname'=>'JO', 'name'=>'Jordan', 'phone_code'=>'+962', 'status'=>'1'],
            ['shortname'=>'KZ', 'name'=>'Kazakhstan', 'phone_code'=>'+7', 'status'=>'1'],
            ['shortname'=>'KE', 'name'=>'Kenya', 'phone_code'=>'+254', 'status'=>'1'],
            ['shortname'=>'KI', 'name'=>'Kiribati', 'phone_code'=>'+686', 'status'=>'1'],
            ['shortname'=>'KP', 'name'=>'Korea North', 'phone_code'=>'+850', 'status'=>'1'],
            ['shortname'=>'KR', 'name'=>'Korea South', 'phone_code'=>'+82', 'status'=>'1'],
            ['shortname'=>'KW', 'name'=>'Kuwait', 'phone_code'=>'+965', 'status'=>'1'],
            ['shortname'=>'KG', 'name'=>'Kyrgyzstan', 'phone_code'=>'+996', 'status'=>'1'],
            ['shortname'=>'LA', 'name'=>'Laos', 'phone_code'=>'+856', 'status'=>'1'],
            ['shortname'=>'LV', 'name'=>'Latvia', 'phone_code'=>'+371', 'status'=>'1'],
            ['shortname'=>'LB', 'name'=>'Lebanon', 'phone_code'=>'+961', 'status'=>'1'],
            ['shortname'=>'LS', 'name'=>'Lesotho', 'phone_code'=>'+266', 'status'=>'1'],
            ['shortname'=>'LR', 'name'=>'Liberia', 'phone_code'=>'+231', 'status'=>'1'],
            ['shortname'=>'LY', 'name'=>'Libya', 'phone_code'=>'+218', 'status'=>'1'],
            ['shortname'=>'LI', 'name'=>'Liechtenstein', 'phone_code'=>'+423', 'status'=>'1'],
            ['shortname'=>'LT', 'name'=>'Lithuania', 'phone_code'=>'+370', 'status'=>'1'],
            ['shortname'=>'LU', 'name'=>'Luxembourg', 'phone_code'=>'+352', 'status'=>'1'],
            ['shortname'=>'MO', 'name'=>'Macau S.A.R.', 'phone_code'=>'+853', 'status'=>'1'],
            ['shortname'=>'MK', 'name'=>'Macedonia', 'phone_code'=>'+389', 'status'=>'1'],
            ['shortname'=>'MG', 'name'=>'Madagascar', 'phone_code'=>'+261', 'status'=>'1'],
            ['shortname'=>'MW', 'name'=>'Malawi', 'phone_code'=>'+265', 'status'=>'1'],
            ['shortname'=>'MY', 'name'=>'Malaysia', 'phone_code'=>'+60', 'status'=>'1'],
            ['shortname'=>'MV', 'name'=>'Maldives', 'phone_code'=>'+960', 'status'=>'1'],
            ['shortname'=>'ML', 'name'=>'Mali', 'phone_code'=>'+223', 'status'=>'1'],
            ['shortname'=>'MT', 'name'=>'Malta', 'phone_code'=>'+356', 'status'=>'1'],
            ['shortname'=>'XM', 'name'=>'Man (Isle of)', 'phone_code'=>'+44', 'status'=>'1'],
            ['shortname'=>'MH', 'name'=>'Marshall Islands', 'phone_code'=>'+692', 'status'=>'1'],
            ['shortname'=>'MQ', 'name'=>'Martinique', 'phone_code'=>'+596', 'status'=>'1'],
            ['shortname'=>'MR', 'name'=>'Mauritania', 'phone_code'=>'+222', 'status'=>'1'],
            ['shortname'=>'MU', 'name'=>'Mauritius', 'phone_code'=>'+230', 'status'=>'1'],
            ['shortname'=>'YT', 'name'=>'Mayotte', 'phone_code'=>'+269', 'status'=>'1'],
            ['shortname'=>'MX', 'name'=>'Mexico', 'phone_code'=>'+52', 'status'=>'1'],
            ['shortname'=>'FM', 'name'=>'Micronesia', 'phone_code'=>'+691', 'status'=>'1'],
            ['shortname'=>'MD', 'name'=>'Moldova', 'phone_code'=>'+373', 'status'=>'1'],
            ['shortname'=>'MC', 'name'=>'Monaco', 'phone_code'=>'+377', 'status'=>'1'],
            ['shortname'=>'MN', 'name'=>'Mongolia', 'phone_code'=>'+976', 'status'=>'1'],
            ['shortname'=>'MS', 'name'=>'Montserrat', 'phone_code'=>'+1664', 'status'=>'1'],
            ['shortname'=>'MA', 'name'=>'Morocco', 'phone_code'=>'+212', 'status'=>'1'],
            ['shortname'=>'MZ', 'name'=>'Mozambique', 'phone_code'=>'+258', 'status'=>'1'],
            ['shortname'=>'MM', 'name'=>'Myanmar', 'phone_code'=>'+95', 'status'=>'1'],
            ['shortname'=>'NA', 'name'=>'Namibia', 'phone_code'=>'+264', 'status'=>'1'],
            ['shortname'=>'NR', 'name'=>'Nauru', 'phone_code'=>'+674', 'status'=>'1'],
            ['shortname'=>'NP', 'name'=>'Nepal', 'phone_code'=>'+977', 'status'=>'1'],
            ['shortname'=>'AN', 'name'=>'Netherlands Antilles', 'phone_code'=>'+599', 'status'=>'1'],
            ['shortname'=>'NL', 'name'=>'Netherlands The', 'phone_code'=>'+31', 'status'=>'1'],
            ['shortname'=>'NC', 'name'=>'New Caledonia', 'phone_code'=>'+687', 'status'=>'1'],
            ['shortname'=>'NZ', 'name'=>'New Zealand', 'phone_code'=>'+64', 'status'=>'1'],
            ['shortname'=>'NI', 'name'=>'Nicaragua', 'phone_code'=>'+505', 'status'=>'1'],
            ['shortname'=>'NE', 'name'=>'Niger', 'phone_code'=>'+227', 'status'=>'1'],
            ['shortname'=>'NG', 'name'=>'Nigeria', 'phone_code'=>'+234', 'status'=>'1'],
            ['shortname'=>'NU', 'name'=>'Niue', 'phone_code'=>'+683', 'status'=>'1'],
            ['shortname'=>'NF', 'name'=>'Norfolk Island', 'phone_code'=>'+672', 'status'=>'1'],
            ['shortname'=>'MP', 'name'=>'Northern Mariana Islands', 'phone_code'=>'+1670', 'status'=>'1'],
            ['shortname'=>'NO', 'name'=>'Norway', 'phone_code'=>'+47', 'status'=>'1'],
            ['shortname'=>'OM', 'name'=>'Oman', 'phone_code'=>'+968', 'status'=>'1'],
            ['shortname'=>'PK', 'name'=>'Pakistan', 'phone_code'=>'+92', 'status'=>'1'],
            ['shortname'=>'PW', 'name'=>'Palau', 'phone_code'=>'+680', 'status'=>'1'],
            ['shortname'=>'PS', 'name'=>'Palestinian Territory Occupied', 'phone_code'=>'+970', 'status'=>'1'],
            ['shortname'=>'PA', 'name'=>'Panama', 'phone_code'=>'+507', 'status'=>'1'],
            ['shortname'=>'PG', 'name'=>'Papua new Guinea', 'phone_code'=>'+675', 'status'=>'1'],
            ['shortname'=>'PY', 'name'=>'Paraguay', 'phone_code'=>'+595', 'status'=>'1'],
            ['shortname'=>'PE', 'name'=>'Peru', 'phone_code'=>'+51', 'status'=>'1'],
            ['shortname'=>'PH', 'name'=>'Philippines', 'phone_code'=>'+63', 'status'=>'1'],
            ['shortname'=>'PN', 'name'=>'Pitcairn Island', 'phone_code'=>'+0', 'status'=>'1'],
            ['shortname'=>'PL', 'name'=>'Poland', 'phone_code'=>'+48', 'status'=>'1'],
            ['shortname'=>'PT', 'name'=>'Portugal', 'phone_code'=>'+351', 'status'=>'1'],
            ['shortname'=>'PR', 'name'=>'Puerto Rico', 'phone_code'=>'+1787', 'status'=>'1'],
            ['shortname'=>'QA', 'name'=>'Qatar', 'phone_code'=>'+974', 'status'=>'1'],
            ['shortname'=>'RE', 'name'=>'Reunion', 'phone_code'=>'+262', 'status'=>'1'],
            ['shortname'=>'RO', 'name'=>'Romania', 'phone_code'=>'+40', 'status'=>'1'],
            ['shortname'=>'RU', 'name'=>'Russia', 'phone_code'=>'+70', 'status'=>'1'],
            ['shortname'=>'RW', 'name'=>'Rwanda', 'phone_code'=>'+250', 'status'=>'1'],
            ['shortname'=>'SH', 'name'=>'Saint Helena', 'phone_code'=>'+290', 'status'=>'1'],
            ['shortname'=>'KN', 'name'=>'Saint Kitts And Nevis', 'phone_code'=>'+1869', 'status'=>'1'],
            ['shortname'=>'LC', 'name'=>'Saint Lucia', 'phone_code'=>'+1758', 'status'=>'1'],
            ['shortname'=>'PM', 'name'=>'Saint Pierre and Miquelon', 'phone_code'=>'+508', 'status'=>'1'],
            ['shortname'=>'VC', 'name'=>'Saint Vincent And The Grenadines', 'phone_code'=>'+1784', 'status'=>'1'],
            ['shortname'=>'WS', 'name'=>'Samoa', 'phone_code'=>'+684', 'status'=>'1'],
            ['shortname'=>'SM', 'name'=>'San Marino', 'phone_code'=>'+378', 'status'=>'1'],
            ['shortname'=>'ST', 'name'=>'Sao Tome and Principe', 'phone_code'=>'+239', 'status'=>'1'],
            ['shortname'=>'SA', 'name'=>'Saudi Arabia', 'phone_code'=>'+966', 'status'=>'1'],
            ['shortname'=>'SN', 'name'=>'Senegal', 'phone_code'=>'+221', 'status'=>'1'],
            ['shortname'=>'RS', 'name'=>'Serbia', 'phone_code'=>'+381', 'status'=>'1'],
            ['shortname'=>'SC', 'name'=>'Seychelles', 'phone_code'=>'+248', 'status'=>'1'],
            ['shortname'=>'SL', 'name'=>'Sierra Leone', 'phone_code'=>'+232', 'status'=>'1'],
            ['shortname'=>'SG', 'name'=>'Singapore', 'phone_code'=>'+65', 'status'=>'1'],
            ['shortname'=>'SK', 'name'=>'Slovakia', 'phone_code'=>'+421', 'status'=>'1'],
            ['shortname'=>'SI', 'name'=>'Slovenia', 'phone_code'=>'+386', 'status'=>'1'],
            ['shortname'=>'XG', 'name'=>'Smaller Territories of the UK', 'phone_code'=>'+44', 'status'=>'1'],
            ['shortname'=>'SB', 'name'=>'Solomon Islands', 'phone_code'=>'+677', 'status'=>'1'],
            ['shortname'=>'SO', 'name'=>'Somalia', 'phone_code'=>'+252', 'status'=>'1'],
            ['shortname'=>'ZA', 'name'=>'South Africa', 'phone_code'=>'+27', 'status'=>'1'],
            ['shortname'=>'GS', 'name'=>'South Georgia', 'phone_code'=>'+0', 'status'=>'1'],
            ['shortname'=>'SS', 'name'=>'South Sudan', 'phone_code'=>'+211', 'status'=>'1'],
            ['shortname'=>'ES', 'name'=>'Spain', 'phone_code'=>'+34', 'status'=>'1'],
            ['shortname'=>'LK', 'name'=>'Sri Lanka', 'phone_code'=>'+94', 'status'=>'1'],
            ['shortname'=>'SD', 'name'=>'Sudan', 'phone_code'=>'+249', 'status'=>'1'],
            ['shortname'=>'SR', 'name'=>'Suriname', 'phone_code'=>'+597', 'status'=>'1'],
            ['shortname'=>'SJ', 'name'=>'Svalbard And Jan Mayen Islands', 'phone_code'=>'+47', 'status'=>'1'],
            ['shortname'=>'SZ', 'name'=>'Swaziland', 'phone_code'=>'+268', 'status'=>'1'],
            ['shortname'=>'SE', 'name'=>'Sweden', 'phone_code'=>'+46', 'status'=>'1'],
            ['shortname'=>'CH', 'name'=>'Switzerland', 'phone_code'=>'+41', 'status'=>'1'],
            ['shortname'=>'SY', 'name'=>'Syria', 'phone_code'=>'+963', 'status'=>'1'],
            ['shortname'=>'TW', 'name'=>'Taiwan', 'phone_code'=>'+886', 'status'=>'1'],
            ['shortname'=>'TJ', 'name'=>'Tajikistan', 'phone_code'=>'+992', 'status'=>'1'],
            ['shortname'=>'TZ', 'name'=>'Tanzania', 'phone_code'=>'+255', 'status'=>'1'],
            ['shortname'=>'TH', 'name'=>'Thailand', 'phone_code'=>'+66', 'status'=>'1'],
            ['shortname'=>'TG', 'name'=>'Togo', 'phone_code'=>'+228', 'status'=>'1'],
            ['shortname'=>'TK', 'name'=>'Tokelau', 'phone_code'=>'+690', 'status'=>'1'],
            ['shortname'=>'TO', 'name'=>'Tonga', 'phone_code'=>'+676', 'status'=>'1'],
            ['shortname'=>'TT', 'name'=>'Trinidad And Tobago', 'phone_code'=>'+1868', 'status'=>'1'],
            ['shortname'=>'TN', 'name'=>'Tunisia', 'phone_code'=>'+216', 'status'=>'1'],
            ['shortname'=>'TR', 'name'=>'Turkey', 'phone_code'=>'+90', 'status'=>'1'],
            ['shortname'=>'TM', 'name'=>'Turkmenistan', 'phone_code'=>'+7370', 'status'=>'1'],
            ['shortname'=>'TC', 'name'=>'Turks And Caicos Islands', 'phone_code'=>'+1649', 'status'=>'1'],
            ['shortname'=>'TV', 'name'=>'Tuvalu', 'phone_code'=>'+688', 'status'=>'1'],
            ['shortname'=>'UG', 'name'=>'Uganda', 'phone_code'=>'+256', 'status'=>'1'],
            ['shortname'=>'UA', 'name'=>'Ukraine', 'phone_code'=>'+380', 'status'=>'1'],
            ['shortname'=>'AE', 'name'=>'United Arab Emirates', 'phone_code'=>'+971', 'status'=>'1'],
            ['shortname'=>'GB', 'name'=>'United Kingdom', 'phone_code'=>'+44', 'status'=>'1'],
            ['shortname'=>'US', 'name'=>'United States', 'phone_code'=>'+1', 'status'=>'1'],
            ['shortname'=>'UM', 'name'=>'United States Minor Outlying Islands', 'phone_code'=>'+1', 'status'=>'1'],
            ['shortname'=>'UY', 'name'=>'Uruguay', 'phone_code'=>'+598', 'status'=>'1'],
            ['shortname'=>'UZ', 'name'=>'Uzbekistan', 'phone_code'=>'+998', 'status'=>'1'],
            ['shortname'=>'VU', 'name'=>'Vanuatu', 'phone_code'=>'+678', 'status'=>'1'],
            ['shortname'=>'VA', 'name'=>'Vatican City State (Holy See)', 'phone_code'=>'+39', 'status'=>'1'],
            ['shortname'=>'VE', 'name'=>'Venezuela', 'phone_code'=>'+58', 'status'=>'1'],
            ['shortname'=>'VN', 'name'=>'Vietnam', 'phone_code'=>'+84', 'status'=>'1'],
            ['shortname'=>'VG', 'name'=>'Virgin Islands (British)', 'phone_code'=>'+1284', 'status'=>'1'],
            ['shortname'=>'VI', 'name'=>'Virgin Islands (US)', 'phone_code'=>'+1340', 'status'=>'1'],
            ['shortname'=>'WF', 'name'=>'Wallis And Futuna Islands', 'phone_code'=>'+681', 'status'=>'1'],
            ['shortname'=>'EH', 'name'=>'Western Sahara', 'phone_code'=>'+212', 'status'=>'1'],
            ['shortname'=>'YE', 'name'=>'Yemen', 'phone_code'=>'+967', 'status'=>'1'],
            ['shortname'=>'YU', 'name'=>'Yugoslavia', 'phone_code'=>'+38', 'status'=>'1'],
            ['shortname'=>'ZM', 'name'=>'Zambia', 'phone_code'=>'+260', 'status'=>'1'],
            ['shortname'=>'ZW', 'name'=>'Zimbabwe', 'phone_code'=>'+263', 'status'=>'1'],

        ];

         foreach ($country as $key => $value) {
            Country::create($value);
        }
    }
}
